# GitHub Sponsors

github: []

# Open Collective

open_collective:

# Ko-fi

ko_fi:

# Patreon

patreon:

# Buy Me a Coffee

buy_me_a_coffee:

# Polar

polar:

# Tidelift

tidelift:

# Community Bridge

community_bridge:

# Liberapay

liberapay:

# Thanks.dev

thanks_dev:

# Custom funding links

custom:

* https://www.cogosphere.org
* https://github.com/sponsors
